# TODO: Re-enable
# sauce_connect: true
browsers:
  - name: firefox
    version: latest
  - name: chrome
    version: latest
  # TODO: Re-enable
  # - name: safari
  #  version: latest
  - name: edge
    version: latest
  - name: and_chr
    version: latest
  - name: ios_saf
    version: latest
# TODO: Re-enable
# providers:
#  - airtap-sauce
presets:
  local:
    providers: airtap-manual
    browsers:
      - name: manual
browserify:
  - plugin: tsify
