sauce_connect: true
browsers:
  - name: firefox
    version: latest
  - name: chrome
    version: latest
  # FIXME: Safari on macOS via SauceLabs is currently (as of May 22, 2022) not
  # functional due to the dynamic hostname airtap.local not being applied
  # - name: safari
  #  version: latest
  - name: edge
    version: latest
  - name: and_chr
    version: latest
  - name: ios_saf
    version: latest
providers:
  - airtap-sauce
presets:
  local:
    providers: airtap-manual
    browsers:
      - name: manual
browserify:
  - plugin: tsify
